remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Edwin Daniel O単a Simba単a]
description: [Curriculum Vitae]

show_downloads: [false]
#google_analytics: [Your Google Analytics tracking ID]



# theme: jekyll-theme-slate

# title: Edwin Daniel O単a Simba単a
# tagline: edwinDOS
# name: edwinDOS

# url: "http://edwinDOS.github.io"
# baseurl: ""

# # SEO
# twitter:

# username: edwinDOS